# _config.yml — CVE-Search / CveXplore configuration

################################################################################
# 1) Data source
################################################################################

# Tell CveXplore we’re using MongoDB
datasource_type: mongodb

# Explicitly provide the host+port and database name
# (this is the “new” config format; CveXplore will override
# the legacy mongodb_connection_details if present)
datasource_connection_details:
  host:  mongodb://mongo:27017
  database: cvedb

# For backwards‐compatibility you can also include the old key,
# but it isn’t strictly necessary once you’re on the new format.
mongodb_connection_details:
  host:  mongodb://mongo:27017
  database: cvedb

################################################################################
# 2) HTTP API server settings
################################################################################

api_host: 0.0.0.0
api_port: 5000
ssl:      false

################################################################################
# 3) Logging
################################################################################

logging:
  level: INFO
