name: "Cve-Search docker version"

services:

  cve_search:
    image: cve_search
    build:
      context: .
      dockerfile: docker/images/cve_search/dockerfile-cve_search
      args:
        - REPO=cve-search/cve-search
        - BRANCH=master
    hostname: cve_search
    volumes:
      - ./.config.yml:/app/.config.yml:ro
      - ./cve_backfill.sh:/app/cve_backfill.sh:ro
      - ./Sources_process.py:/app/lib/Sources_process.py:ro
    depends_on:
      redis:
        condition: service_healthy
      mongo:
        condition: service_healthy
    restart: always
    labels:
      - "autoheal=true"
    environment:
      - PYTHONUNBUFFERED=TRUE
      - WORKER_SIZE=1
      - NVD_NIST_API_KEY=<your-key-here>
      - MONGODB_HOST=mongo
    ports:
      - '5000:5000'
    networks:
      - frontend
      - backend
    healthcheck:
      test: curl --fail https://localhost:5000 -k || exit 1
      interval: 30s
      timeout: 5s
      retries: 1
      start_period: 5s

  redis:
    image: cve_search-redis
    hostname: redis
    restart: always
    labels:
      - "autoheal=true"
    build:
      context: .
      dockerfile: docker/images/redis/dockerfile-redis
    volumes:
      - redis_data:/data
    expose:
      - 6379
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 30s
      timeout: 5s
      retries: 1
      start_period: 30s

  mongo:
    image: cve_search-mongo
    hostname: mongo
    restart: always
    labels:
      - "autoheal=true"
    build:
      context: .
      dockerfile: docker/images/mongodb/dockerfile-mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend
    command: [ "mongod", "--bind_ip_all" ]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 10s

  cvelist_importer:
    build:
      context: .
      dockerfile: importer/Dockerfile
    volumes:
      - .:/opt/app
    working_dir: /opt/app/importer
    command: >
      bash -lc "
        python import_cvelistv5.py &&
        python build_mapping.py
      "
    depends_on:
      mongo:
        condition: service_started
    networks:
      - backend

  vendor_product_api:
    build:
      context: .
      dockerfile: Dockerfile.api
    volumes:
      - .:/opt/app:delegated
    ports:
      - "8000:8000"
    environment:
      MONGO_URI:        "mongodb://mongo:27017/"
      DB_NAME:          "cvedb"
      NVD_COLL:         "cves"
      CVELIST_COLL:     "cvelistv5"
      MAP_NVD_COLL:     "map_vendor_product_nvd"
      MAP_CVELIST_COLL: "map_vendor_product_cvelistv5"
      API_PORT:         "8000"
    command:
      - uvicorn
      - vendor_product_api:app
      - --host
      - "0.0.0.0"
      - --port
      - "8000"
    depends_on:
      - mongo
    networks:
      - backend

  autoheal:
    image: willfarrell/autoheal:latest
    hostname: autoheal
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  mongodb_data:
  redis_data:
